import assert from "node:assert/strict";
import test from "node:test";

import { defineConfig, renderMarkdown } from "../dist/core.js";

test("renders frames outer-first and closes them in reverse order", async () => {
  const result = await renderMarkdown(
    "# Body\n",
    [
      { opening: "<!-- outer opening -->\n", closing: "\n<!-- outer closing -->" },
      { opening: "<!-- inner opening -->\n", closing: "\n<!-- inner closing -->" },
    ],
    { sourceName: "SOURCE.md" },
  );

  const markers = [
    "<!-- outer opening -->",
    "<!-- inner opening -->",
    "# Body",
    "<!-- inner closing -->",
    "<!-- outer closing -->",
  ];
  let previous = -1;
  for (const marker of markers) {
    const position = result.indexOf(marker);
    assert.notEqual(position, -1, `missing ${marker}`);
    assert.ok(position > previous, `${marker} is out of order`);
    previous = position;
  }
  assert.match(result, /^<!-- This file is generated by mdtheme\. Edit SOURCE\.md instead\. -->/);
});

test("supports zero themes and empty frame parts", async () => {
  const source = "# Plain\n";
  const zero = await renderMarkdown(source, []);
  const empty = await renderMarkdown(source, [{ opening: "", closing: "" }]);

  assert.equal(zero, empty);
  assert.match(zero, /# Plain/);
});

test("separates frame sections when factories omit newlines", async () => {
  const result = await renderMarkdown("# Project\n\n    indented code\n", [
    { opening: "# Brand", closing: "Footer" },
  ]);

  assert.ok(result.indexOf("# Brand") < result.indexOf("# Project"));
  assert.ok(result.indexOf("# Project") < result.indexOf("Footer"));
  assert.match(result, /# Brand\n\n# Project/);
  assert.match(result, / {4}indented code/);
  assert.match(result, /indented code\n\nFooter/);
});

test("keeps multiline Markdown constructs intact", async () => {
  const source = [
    "# Heading",
    "",
    "A paragraph with a [reference link][docs] and an image ![logo](logo.png).",
    "",
    "```js",
    "const answer = 42;",
    "```",
    "",
    "    indented code",
    "",
    "[docs]: https://example.com/docs",
    "",
  ].join("\n");
  const result = await renderMarkdown(source, []);

  assert.match(result, /\[reference link\]\[docs\]/);
  assert.match(result, /!\[logo\]\(logo\.png\)/);
  assert.match(result, /```js\nconst answer = 42;\n```/);
  assert.match(result, / {4}indented code/);
  assert.match(result, /\[docs\]: https:\/\/example\.com\/docs/);
});

test("does not reformat fenced code embedded in Markdown", async () => {
  const source = ["```js", "function  unusual( ){return 1}", "```", ""].join("\n");
  const result = await renderMarkdown(source, []);

  assert.match(result, /```js\nfunction {2}unusual\( \)\{return 1\}\n```/);
});

test("preserves authored Markdown, whitespace, and line endings", async () => {
  const source = [
    "Heading",
    "=======",
    "",
    "*   First item  ",
    "    continued",
    "",
    "|Name|Value|",
    "|---|---|",
    "|One|Two|",
    "",
    "```js",
    "function  unusual( ){return 1}",
    "```",
    "",
    "    indented code",
    "",
    "",
  ].join("\r\n");
  const opening = "<!-- authored opening -->\r\n\r\n";
  const closing = "<!-- authored closing -->\r\n\r\n\r\n";
  const result = await renderMarkdown(source, [{ opening, closing }]);

  assert.equal(
    result,
    `<!-- This file is generated by mdtheme. Edit README.md.src instead. -->\n\n${opening}${source}${closing}`,
  );
});

test("preserves a missing final newline", async () => {
  const result = await renderMarkdown("# Heading", []);
  assert.equal(
    result,
    "<!-- This file is generated by mdtheme. Edit README.md.src instead. -->\n\n# Heading",
  );
});

test("defineConfig applies defaults and does not mutate input", () => {
  const frame = { opening: "<!-- open -->", closing: "<!-- close -->" };
  const input = { themes: [frame] };
  const normalized = defineConfig(input);

  assert.deepEqual(normalized, {
    source: "README.md.src",
    output: "README.md",
    themes: [frame],
  });
  assert.notEqual(normalized, input);
  assert.notEqual(normalized.themes, input.themes);
  assert.notEqual(normalized.themes[0], frame);
  assert.deepEqual(input, { themes: [frame] });
});

test("rejects malformed and sparse frames", () => {
  assert.throws(() => defineConfig({ themes: [{ opening: "ok" }] }), /closing/);
  assert.throws(() => defineConfig({ themes: [{ opening: 1, closing: "ok" }] }), /opening/);
  assert.throws(
    () => defineConfig({ themes: [{ opening: "ok", closing: "ok", extra: true }] }),
    /unknown key/,
  );
  assert.throws(() => defineConfig({ themes: [null] }), /themes\[0\]/);

  const sparse = [];
  sparse.length = 1;
  assert.throws(() => defineConfig({ themes: sparse }), /sparse/);
});

test("rejects unknown config keys and unsafe source names", async () => {
  assert.throws(() => defineConfig({ themes: [], extra: true }), /unknown config key/);
  await assert.rejects(
    () => renderMarkdown("# Body", [], { sourceName: "../evil.md" }),
    /sourceName/,
  );
  await assert.rejects(
    () => renderMarkdown("# Body", [], { sourceName: "evil\n<!-- -->" }),
    /sourceName/,
  );
});

test("rendering does not mutate source or frame inputs", async () => {
  const source = "# Body\n";
  const themes = [
    { opening: "<!-- A -->\n", closing: "\n<!-- /A -->" },
    { opening: "<!-- B -->\n", closing: "\n<!-- /B -->" },
  ];
  const sourceBefore = source;
  const themesBefore = structuredClone(themes);

  const first = await renderMarkdown(source, themes);
  const second = await renderMarkdown(source, themes);

  assert.equal(first, second);
  assert.equal(source, sourceBefore);
  assert.deepEqual(themes, themesBefore);
});
