use std::{
    fs,
    path::Path,
    process::{Command, Output},
};
use tempfile::{TempDir, tempdir};

fn invoke(root: &Path, args: &[&str]) -> Output {
    Command::new(env!("CARGO_BIN_EXE_mdtheme"))
        .args(args)
        .current_dir(root)
        .output()
        .unwrap()
}
fn expect(root: &Path, args: &[&str], code: i32) -> Output {
    let result = invoke(root, args);
    assert_eq!(
        result.status.code(),
        Some(code),
        "args: {args:?}\nstdout: {}\nstderr: {}",
        String::from_utf8_lossy(&result.stdout),
        String::from_utf8_lossy(&result.stderr)
    );
    result
}
fn fixture() -> TempDir {
    let root = tempdir().unwrap();
    fs::write(
        root.path().join("README.md.src"),
        "# Hello\n\nThis is authored prose.\n",
    )
    .unwrap();
    root
}
fn read(root: &Path) -> String {
    fs::read_to_string(root.join("README.md")).unwrap()
}

#[test]
fn write_and_read_only_check_preserve_files() {
    let root = fixture();
    let root = root.path();
    expect(root, &["--check"], 1);
    assert!(!root.join("README.md").exists());
    expect(root, &["--write"], 0);
    let before = fs::metadata(root.join("README.md"))
        .unwrap()
        .modified()
        .unwrap();
    expect(root, &["--check"], 0);
    expect(root, &["--write"], 0);
    assert_eq!(
        fs::metadata(root.join("README.md"))
            .unwrap()
            .modified()
            .unwrap(),
        before
    );
    fs::write(root.join("README.md"), "drift\n").unwrap();
    expect(root, &["--check"], 1);
    assert_eq!(read(root), "drift\n");
    assert_eq!(fs::read_dir(root).unwrap().count(), 2);
}

#[test]
fn themes_nest_and_preserve_authored_markdown() {
    let root = fixture();
    let root = root.path();
    let source = "Heading\r\n=======\r\n\r\n*   Item  \r\n\r\n```js\r\nfunction  unusual( ){return 1}\r\n```\r\n\r\n    code\r\n\r\n";
    fs::write(root.join("README.md.src"), source).unwrap();
    for (theme, opening, closing) in [
        ("outer", "<!-- outer -->\r\n\r\n", "<!-- /outer -->"),
        ("inner", "<!-- inner -->\n\n", "<!-- /inner -->\n\n"),
    ] {
        fs::create_dir(root.join(theme)).unwrap();
        fs::write(root.join(theme).join("header.md"), opening).unwrap();
        fs::write(root.join(theme).join("footer.md"), closing).unwrap();
    }
    fs::write(
        root.join("mdtheme.yaml"),
        "themes:\n  - directory: outer\n  - directory: inner\n",
    )
    .unwrap();
    expect(root, &["--write"], 0);
    let result = read(root);
    assert!(result.contains(source));
    let markers = [
        "<!-- outer -->",
        "<!-- inner -->",
        "Heading",
        "<!-- /inner -->",
        "<!-- /outer -->",
    ];
    let positions: Vec<_> = markers
        .iter()
        .map(|marker| result.find(marker).unwrap())
        .collect();
    assert!(positions.windows(2).all(|pair| pair[0] < pair[1]));
    assert_eq!(
        fs::read_to_string(root.join("README.md.src")).unwrap(),
        source
    );
    let first = result;
    expect(root, &["--write"], 0);
    assert_eq!(read(root), first);
}

#[test]
fn preserves_missing_final_newline_and_empty_config_defaults() {
    let root = fixture();
    let root = root.path();
    fs::write(root.join("README.md.src"), "# Heading").unwrap();
    fs::write(root.join("mdtheme.yaml"), "").unwrap();
    expect(root, &["--write"], 0);
    assert_eq!(
        read(root),
        "<!-- This file is generated by mdtheme. Edit README.md.src instead. -->\n\n# Heading"
    );
}

#[test]
fn unsafe_paths_and_invalid_configs_fail_before_mutation() {
    let root = fixture();
    let root = root.path();
    fs::write(root.join("README.md"), "keep me\n").unwrap();
    for config in [
        "source: README.md\n",
        "source: ../README.md.src\n",
        "output: other/README.md\n",
        "output: OTHER.md\n",
        "unknown: true\n",
        "themes: [null]\n",
        "themes: [{directory: x, unknown: true}]\n",
        "themes: [\n",
    ] {
        fs::write(root.join("mdtheme.yaml"), config).unwrap();
        expect(root, &["--write"], 2);
        assert_eq!(read(root), "keep me\n", "config: {config}");
    }
    fs::write(root.join("mdtheme.yaml"), "{}\n").unwrap();
    fs::remove_file(root.join("README.md.src")).unwrap();
    expect(root, &["--write"], 2);
    assert_eq!(read(root), "keep me\n");
}

#[test]
fn hardlinked_output_is_rejected_without_changing_source() {
    let root = fixture();
    let root = root.path();
    let before = fs::read(root.join("README.md.src")).unwrap();
    fs::hard_link(root.join("README.md.src"), root.join("README.md")).unwrap();
    expect(root, &["--write"], 2);
    assert_eq!(fs::read(root.join("README.md.src")).unwrap(), before);
}

#[cfg(unix)]
#[test]
fn symlinked_output_is_rejected_and_binary_symlink_works() {
    use std::os::unix::fs::symlink;
    let root = fixture();
    let root = root.path();
    symlink("README.md.src", root.join("README.md")).unwrap();
    expect(root, &["--write"], 2);
    assert!(
        fs::symlink_metadata(root.join("README.md"))
            .unwrap()
            .is_symlink()
    );
    let binary = root.join("mdtheme");
    symlink(env!("CARGO_BIN_EXE_mdtheme"), &binary).unwrap();
    let result = Command::new(binary).arg("--version").output().unwrap();
    assert!(result.status.success());
    assert!(String::from_utf8_lossy(&result.stdout).contains(env!("CARGO_PKG_VERSION")));
}

#[test]
fn explicit_config_uses_its_directory_and_discovery_rejects_ambiguity() {
    let caller = tempdir().unwrap();
    let project = fixture();
    let root = project.path();
    fs::write(root.join("mdtheme.yaml"), "{}\n").unwrap();
    fs::write(root.join("mdtheme.yml"), "{}\n").unwrap();
    expect(root, &["--write"], 2);
    let config = root.join("mdtheme.yaml");
    expect(
        caller.path(),
        &["--write", "--config", config.to_str().unwrap()],
        0,
    );
    assert!(read(root).contains("# Hello"));
    assert!(!caller.path().join("README.md").exists());
}

#[test]
fn help_version_and_argument_errors_do_not_write() {
    let root = fixture();
    let root = root.path();
    let help = expect(root, &["--help"], 0);
    assert!(String::from_utf8_lossy(&help.stdout).contains("mdtheme"));
    let version = expect(root, &["--version"], 0);
    assert!(String::from_utf8_lossy(&version.stdout).contains(env!("CARGO_PKG_VERSION")));
    for args in [
        &["--write", "--check"][..],
        &["pre-push", "--write"],
        &["--nope"],
        &["--config"],
        &["constructor"],
        &["toString"],
        &["__proto__"],
    ] {
        expect(root, args, 2);
        assert!(!root.join("README.md").exists());
    }
}

#[test]
fn executable_configs_require_migration_and_are_never_run() {
    let directory = fixture();
    let root = directory.path();
    fs::write(root.join("mdtheme.config.mjs"), "import { writeFileSync } from 'node:fs';\nwriteFileSync('executed.txt', 'bad');\nexport default {};\n").unwrap();
    expect(root, &["--write"], 2);
    assert!(!root.join("executed.txt").exists());
    assert!(!root.join("README.md").exists());
}
