import { execFile } from "node:child_process";
import { mkdtemp, readFile, rm, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);
const packageRoot = process.cwd();
const offline = process.env.MARKDOWN_THEMER_VERIFY_OFFLINE === "1";
const suppliedNpmCache = process.env.MARKDOWN_THEMER_VERIFY_NPM_CACHE;

async function run(command, args, options) {
  const { cwd, expectedCodes = [0] } = options;
  try {
    const result = await execFileAsync(command, args, {
      cwd,
      env: {
        ...process.env,
        ...(npmCache ? { npm_config_cache: npmCache } : {}),
      },
      maxBuffer: 1024 * 1024 * 8,
    });
    return { ...result, code: 0 };
  } catch (error) {
    const code = typeof error.code === "number" ? error.code : 1;
    const stdout = error.stdout ?? "";
    const stderr = error.stderr ?? "";
    if (!expectedCodes.includes(code)) {
      throw new Error(`${command} ${args.join(" ")} exited with ${code}\n${stdout}${stderr}`, {
        cause: error,
      });
    }
    return { stdout, stderr, code };
  }
}

function assert(condition, message) {
  if (!condition) throw new Error(message);
}

const scratchRoot = await mkdtemp(join(tmpdir(), "markdown-themer-verify-"));
const packRoot = await mkdtemp(join(tmpdir(), "markdown-themer-pack-"));
const npmCache = suppliedNpmCache ?? (offline ? undefined : join(scratchRoot, ".npm-cache"));

try {
  const packed = await run("npm", ["pack", "--json", "--pack-destination", packRoot], {
    cwd: packageRoot,
  });
  const packResult = JSON.parse(packed.stdout);
  assert(
    Array.isArray(packResult) && packResult[0]?.filename,
    "npm pack did not return a tarball filename",
  );
  const tarball = join(packRoot, packResult[0].filename);

  await run("npm", ["init", "--yes"], { cwd: scratchRoot });
  const installArgs = ["install", "--ignore-scripts"];
  if (offline) installArgs.push("--offline");
  installArgs.push(tarball);
  await run("npm", installArgs, { cwd: scratchRoot });

  await writeFile(
    join(scratchRoot, "theme-factory.ts"),
    `import type { MarkdownFrame } from "markdown-themer";\n\nexport function noticeFrame(label: string): MarkdownFrame {\n  return {\n    opening: \`> **\${label}**\\n>\\n\`,\n    closing: "\\n",\n  };\n}\n`,
  );
  await writeFile(
    join(scratchRoot, "markdown-themer.config.ts"),
    `import { defineConfig } from "markdown-themer";\nimport { noticeFrame } from "./theme-factory.ts";\n\nexport default defineConfig({\n  source: "README.md.src",\n  output: "README.md",\n  themes: [noticeFrame("Local consumer")],\n});\n`,
  );
  await writeFile(
    join(scratchRoot, "README.md.src"),
    "# Packed consumer\n\nThis file is rendered from a local TypeScript config.\n",
  );
  await writeFile(
    join(scratchRoot, "consumer-types.ts"),
    `import { defineConfig, renderMarkdown } from "markdown-themer";\nimport type { Config, MarkdownFrame } from "markdown-themer";\n\nconst frame: MarkdownFrame = { opening: "<section>\\n", closing: "\\n</section>\\n" };\nconst config: Config = defineConfig({ themes: [frame] });\nvoid config;\nvoid renderMarkdown("# Types\\n", [frame]);\n`,
  );
  await writeFile(
    join(scratchRoot, "tsconfig.json"),
    JSON.stringify(
      {
        compilerOptions: {
          target: "ES2024",
          module: "NodeNext",
          moduleResolution: "NodeNext",
          strict: true,
          noEmit: true,
        },
        files: ["consumer-types.ts"],
      },
      null,
      2,
    ),
  );

  const tsc = resolve(packageRoot, "node_modules/.bin/tsc");
  await run(tsc, ["--project", join(scratchRoot, "tsconfig.json")], { cwd: scratchRoot });

  const apiCheck = join(scratchRoot, "api-check.mjs");
  await writeFile(
    apiCheck,
    `import { defineConfig, renderMarkdown } from "markdown-themer";\n\nconst config = defineConfig({ themes: [{ opening: "<section>\\n", closing: "\\n</section>\\n" }] });\nconst output = await renderMarkdown("# API\\n", config.themes);\nif (typeof output !== "string" || !output.includes("# API")) process.exit(1);\n`,
  );
  await run(process.execPath, [apiCheck], { cwd: scratchRoot });

  const cli = join(scratchRoot, "node_modules/.bin/markdown-themer");
  const source = join(scratchRoot, "README.md.src");
  const output = join(scratchRoot, "README.md");
  const sourceBefore = await readFile(source);
  await run(cli, ["--write"], { cwd: scratchRoot });
  const generated = await readFile(output, "utf8");
  assert(
    generated.includes("This file is generated by markdown-themer"),
    "CLI output is missing the generated notice",
  );
  assert(
    generated.includes("Local consumer"),
    "CLI did not load the local TypeScript theme factory",
  );
  assert(generated.includes("# Packed consumer"), "CLI output does not contain source Markdown");
  await run(cli, ["--check"], { cwd: scratchRoot });

  const packagedExampleConfig = join(
    scratchRoot,
    "node_modules/markdown-themer/examples/neutral/markdown-themer.config.ts",
  );
  await run(cli, ["--check", "--config", packagedExampleConfig], { cwd: scratchRoot });

  const beforeCheck = await readFile(output);
  const drifted = Buffer.concat([beforeCheck, Buffer.from("\nDrift introduced by verifier.\n")]);
  await writeFile(output, drifted);
  const driftStat = await stat(output);
  const check = await run(cli, ["--check"], { cwd: scratchRoot, expectedCodes: [1] });
  assert(check.code === 1, "CLI check did not report drift with exit status 1");
  const afterCheck = await readFile(output);
  const afterCheckStat = await stat(output);
  assert(Buffer.compare(afterCheck, drifted) === 0, "CLI check unexpectedly rewrote output");
  assert(afterCheckStat.mtimeMs === driftStat.mtimeMs, "CLI check changed output metadata");

  await run(cli, ["--write"], { cwd: scratchRoot });
  await run(cli, ["--check"], { cwd: scratchRoot });
  const sourceAfter = await readFile(source);
  assert(Buffer.compare(sourceAfter, sourceBefore) === 0, "CLI write mutated the source file");
  console.log("markdown-themer package consumer verification passed");
} finally {
  await Promise.all([
    rm(scratchRoot, { recursive: true, force: true }),
    rm(packRoot, { recursive: true, force: true }),
  ]);
}
