//! Markdown composition without reformatting authored text.

pub mod badges;
pub mod config;
pub mod files;
pub mod metadata;
pub mod pre_push;
pub mod themes;

use anyhow::{Result, ensure};

/// Opening and closing Markdown, supplied outermost first.
#[derive(Debug, Default, Clone)]
pub struct Frame {
    pub opening: String,
    pub closing: String,
}

/// Render a notice and nested frames, preserving every supplied byte of UTF-8 text.
pub fn render(source: &str, frames: &[Frame], source_name: &str) -> Result<String> {
    ensure!(
        safe_source_name(source_name),
        "source must be a simple basename using letters, numbers, ., _, or -"
    );
    let notice = format!("<!-- This file is generated by mdtheme. Edit {source_name} instead. -->");
    let mut parts = vec![notice.as_str()];
    parts.extend(frames.iter().map(|frame| frame.opening.as_str()));
    parts.push(source);
    parts.extend(frames.iter().rev().map(|frame| frame.closing.as_str()));
    let mut result = String::new();
    for part in parts.into_iter().filter(|part| !part.is_empty()) {
        if !result.is_empty() {
            let mut tail = result.as_bytes();
            let mut lines = 0;
            while lines < 2 && tail.last() == Some(&b'\n') {
                tail = &tail[..tail.len() - 1];
                if tail.last() == Some(&b'\r') {
                    tail = &tail[..tail.len() - 1];
                }
                lines += 1;
            }
            result.push_str(&"\n".repeat(2 - lines));
        }
        result.push_str(part);
    }
    Ok(result)
}

pub fn safe_source_name(name: &str) -> bool {
    name.as_bytes()
        .first()
        .is_some_and(u8::is_ascii_alphanumeric)
        && name
            .bytes()
            .all(|c| c.is_ascii_alphanumeric() || b"._-".contains(&c))
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn preserves_source_and_nesting() {
        let frames = vec![
            Frame {
                opening: "A\r\n".into(),
                closing: "a".into(),
            },
            Frame {
                opening: "B".into(),
                closing: "b".into(),
            },
        ];
        assert_eq!(
            render("*   source  \r\n", &frames, "README.md.src").unwrap(),
            "<!-- This file is generated by mdtheme. Edit README.md.src instead. -->\n\nA\r\n\nB\n\n*   source  \r\n\nb\n\na"
        );
    }
    #[test]
    fn rejects_unsafe_notice_names() {
        for name in ["", "../README", "a -->", "é"] {
            assert!(render("", &[], name).is_err());
        }
    }
}
