//! Markdown composition without reformatting authored text.

pub mod badges;
pub mod config;
pub mod files;
pub mod metadata;
mod paths;
pub mod pre_push;
pub mod themes;

use anyhow::{Result, ensure};

/// Opening and closing Markdown, supplied outermost first.
#[derive(Debug, Default, Clone)]
pub struct Frame {
    pub opening: String,
    pub closing: String,
    /// Inline badge fragments inserted before the project badge row.
    pub badges_prepend: String,
    /// Inline badge fragments inserted after the project badge row.
    pub badges_append: String,
}

const BADGES_START: &str = "<!-- mdtheme:badges:start -->";
const BADGES_END: &str = "<!-- mdtheme:badges:end -->";

fn badge_source(source: &str, frames: &[Frame]) -> Result<(String, String)> {
    let starts: Vec<_> = source.match_indices(BADGES_START).collect();
    let ends: Vec<_> = source.match_indices(BADGES_END).collect();
    ensure!(
        (starts.is_empty() && ends.is_empty())
            || (starts.len() == 1 && ends.len() == 1 && starts[0].0 < ends[0].0),
        "Use exactly one ordered pair of mdtheme:badges:start/end markers, or neither"
    );
    let prepend = frames.iter().map(|f| f.badges_prepend.as_str());
    let append = frames.iter().rev().map(|f| f.badges_append.as_str());
    let authored = starts
        .first()
        .map(|(start, _)| &source[start + BADGES_START.len()..ends[0].0])
        .unwrap_or("");
    let row = prepend
        .chain(std::iter::once(authored))
        .chain(append)
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .collect::<Vec<_>>()
        .join(" ");
    if let Some((start, _)) = starts.first() {
        let mut result = source[..*start].to_owned();
        result.push_str(&row);
        result.push_str(&source[ends[0].0 + BADGES_END.len()..]);
        Ok((result, String::new()))
    } else {
        Ok((source.to_owned(), row))
    }
}

/// Render nested frames. Explicit badge slots are composed; other text is preserved.
pub fn render(source: &str, frames: &[Frame], source_name: &str) -> Result<String> {
    ensure!(
        safe_source_name(source_name),
        "source must be a simple basename using letters, numbers, ., _, or -"
    );
    let notice = format!("<!-- This file is generated by mdtheme. Edit {source_name} instead. -->");
    let (source, badge_row) = badge_source(source, frames)?;
    let mut parts = vec![notice.as_str()];
    parts.extend(frames.iter().map(|frame| frame.opening.as_str()));
    parts.push(&badge_row);
    parts.push(&source);
    parts.extend(frames.iter().rev().map(|frame| frame.closing.as_str()));
    let mut result = String::new();
    for part in parts.into_iter().filter(|part| !part.is_empty()) {
        if !result.is_empty() {
            let mut tail = result.as_bytes();
            let mut lines = 0;
            while lines < 2 && tail.last() == Some(&b'\n') {
                tail = &tail[..tail.len() - 1];
                if tail.last() == Some(&b'\r') {
                    tail = &tail[..tail.len() - 1];
                }
                lines += 1;
            }
            result.push_str(&"\n".repeat(2 - lines));
        }
        result.push_str(part);
    }
    Ok(result)
}

pub fn safe_source_name(name: &str) -> bool {
    name.as_bytes()
        .first()
        .is_some_and(u8::is_ascii_alphanumeric)
        && name
            .bytes()
            .all(|c| c.is_ascii_alphanumeric() || b"._-".contains(&c))
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn preserves_source_and_nesting() {
        let frames = vec![
            Frame {
                opening: "A\r\n".into(),
                closing: "a".into(),
                ..Frame::default()
            },
            Frame {
                opening: "B".into(),
                closing: "b".into(),
                ..Frame::default()
            },
        ];
        assert_eq!(
            render("*   source  \r\n", &frames, "README.md.src").unwrap(),
            "<!-- This file is generated by mdtheme. Edit README.md.src instead. -->\n\nA\r\n\nB\n\n*   source  \r\n\nb\n\na"
        );
    }
    #[test]
    fn rejects_unsafe_notice_names() {
        for name in ["", "../README", "a -->", "é"] {
            assert!(render("", &[], name).is_err());
        }
    }
}
